

#         Powered by TabooLib 6.2         #


Settings:
  # 是否在管理员登录游戏时发送鸣谢信息
  send-thank-messages: true
  # 若第一次启动, 则自动释放所有内置附魔
  auto-release-enchants: true
  # 默认附魔品质
  default-rarity: common
  # 如果为附魔主菜单设置了返回按钮, 则点击返回按钮时执行这个命令
  main-menu-back: cd
  # 是否启用命令别称? 启用后将开启 /nereusopus, /nos, /nerous 等命令
  # 这样可以方便从旧插件迁移到新插件, 因为可能有的菜单里打开附魔菜单是调用 /nereusopus menu 这个命令
  # 如果不需要, 将该项设为空集, 例如:
  # command-aliases: [ ]
  # 注: 更改后重启生效
  command-aliases:
#    - se # 该命令别称可能会引起和 CMI 的冲突, 所以默认关闭
    - spe
    - splendidenchants
    - nerous
    - nos
    - nereusopus
  # 是否开启 ItemsAdder 支持
  support-items-adder: true
  # 是否开启脚本预热, 会在附魔加载/重载时编译一次脚本
  # 可以略微提升一点点第一次触发附魔的速度
  enable-kether-preheat: true
  # 对于附魔的挖掘放置攻击生物等操作, OP 是否无视领地等保护
  anti-grief-ignore-op: true
  # 若没有特殊设置, 将冷却消息显示在动作栏而不是聊天框
  cool-down-in-actionbar: false
  # 参数数值保留小数点后几位数字
  variable-rounding-scale: 2
  # 参数数值的舍位模式
  # UP 向远离零的方向舍入 (1.2 -> 2, -1.2 -> -2)
  # DOWN 向零的方向舍入 (1.8 -> 1, -1.8 -> -1)
  # CEILING 向正无穷方向舍入 (1.2 -> 2, -1.2 -> -1)
  # FLOOR 向负无穷方向舍入 (1.8 -> 1, -1.2 -> -2)
  # HALF_UP 四舍五入
  # HALF_DOWN 五舍六入
  # HALF_EVEN 整数位若为奇数则四舍五入, 若为偶数则五舍六入
  # UNNECESSARY 不舍入, 但超出表示范围会报错, 不建议使用
  variable-rounding-mode: HALF_UP
  # 自动更新
  updater:
    # 是否启用平衡性自动更新的功能
    enable: true
    # 附魔平衡性+语言修正调整自动获取官方最新
    contents:
      - "basic.name"
      - "basic.max_level"
      - "alternative"
      - "dependencies"
      - "rarity"
      - "targets"
      - "limitations"
      - "display"
      - "variables"
      - "mechanisms"