name: MMOItems
version: ${project.version}
main: net.Indyuce.mmoitems.MMOItems
author: Indyuce
description: ${project.description}
depend: [MythicLib]
softdepend: [WorldGuard,Residence,BossShopPro,Fabled,SkillsPro,MMOCore,MMOProfiles,MythicMobs,PlaceholderAPI,Vault,Denizen,AureliumSkills,AuraSkills,MythicEnchants]
loadbefore: [MMOInventory, Oraxen]
api-version: 1.14
website: www.phoenixdevt.fr
commands:
    mmoitems:
        description: MMOItems main command.
        aliases: [mi]
    updateitem:
        description: Update the item you are holding.
        aliases: [upitem,itemup]
        permission: mmoitems.update
permissions:
    mmoitems.admin:
        description: Access to admin commands.
        default: op
    mmoitems.update:
        description: Access to /updateitem.
        default: op
    mmoitems.edit.op:
        description: Ability to edit op stats like commands.
        default: false
    mmoitems.bypass.item:
        description: Bypasses item permission restriction.
        default: false
    mmoitems.bypass.ability:
        description: Bypasses ability permission restriction.
        default: false
    mmoitems.bypass.class:
        description: Bypasses item class restriction.
        default: false
    mmoitems.bypass.soulbound:
        description: Bypasses soulbound restriction.
        default: false
    mmoitems.bypass.level:
        description: Bypasses item level restriction.
        default: false
    mmoitems.update-notify:
        description: Receive a notification when a new update is available.
        default: op
    mmoitems.soulbound:
        description: Allows to use /soulbound.
        default: op