# 调试模式
debug: true

# 存储类型: sqlite 或 mysql
database:
  type: "sqlite" # sqlite 或 mysql
  mysql:
    host: "localhost"
    port: 3306
    database: "enchant_disassembler"
    username: "root"
    password: "password"
    table-prefix: "ed_"

# 禁用分解的世界
disabled-worlds:
  - world_creative
  - world_minigames

# 池子大小
pool-sizes:
  common: 20
  uncommon: 15
  rare: 10
  epic: 5
  legendary: 3

# 稀有度别名映射（显示名称 -> 内部 key）
rarity-aliases:
  普通: common
  罕见: uncommon
  精良: rare
  史诗: epic
  传奇: legendary
# 如需自定义，请在此处自行添加/修改。

# 稀有度物品
rarity-items:
  common: PAPER
  uncommon: IRON_INGOT
  rare: GOLD_INGOT
  epic: DIAMOND
  legendary: NETHER_STAR

# 奖励命令（优先级高于 rarity-items）。支持 PlaceholderAPI，占位符 %player% 为玩家名。
reward-commands:
  common:
    - "give %player% minecraft:paper 1"
  uncommon:
    - "give %player% minecraft:iron_ingot 1"
  rare:
    - "give %player% minecraft:gold_ingot 1"
  epic:
    - "give %player% minecraft:diamond 1"
  legendary:
    - "broadcast &6%player% 获得了传奇奖励!"
    - "give %player% minecraft:nether_star 1"
  splendid:
    - "give %player% minecraft:emerald 1"
  artifact:
    - "give %player% minecraft:dragon_breath 1"
# 如需自定义，请修改或追加对应稀有度命令列表。