name: EnchantDisassembler
main: com.magicbili.enchantdisassembler.EnchantDisassembler

version: 1.0.0
author: MaigcBili
description: Enchantment disassembler plugin with GUI support and Aiyatsbus integration
website: https://yourwebsite.com
api-version: 1.20
softdepend: [Aiyatsbus, EcoEnchants]
commands:
  edisassemble:
    description: Open the enchantment disassembler GUI
    aliases: [ed, disassemble]
    usage: /edisassemble
  edisassemble reload:
    description: Reload plugin configuration
    permission: enchantdisassembler.reload
    usage: /edisassemble reload
permissions:
  enchantdisassembler.reload:
    description: Allows reloading the plugin configuration
    default: op
  enchantdisassembler.use:
    description: Allows using the enchantment disassembler
    default: true

# Paper 自动库下载
libraries:
  - mysql:mysql-connector-java:8.0.33
  - org.xerial:sqlite-jdbc:3.44.1.0