

#         Powered by TabooLib 6.2         #


name: Aiyatsbus
main: cc.polarastrum.aiyatsbus.taboolib.platform.BukkitPlugin
version: 1.0.3
authors:
  - 'Mical'
  - 'xiaozhangup'
  - '坏黑'
  - '白熊'
softdepend:
  - 'PlaceholderAPI'
  - 'ItemsAdder'
  - 'BentoBox'
  - 'Residence'
  - 'QuickShop'
  - 'QuickShop-Hikari'
  - 'Citizens'
api-version: 1.17
load: STARTUP
description: Aiyatsbus is a powerful enchantment framework for Paper servers.
folia-supported: true